<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaysSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    private $arguments;
    private $table;

    public function __construct(){
        $this->table='pays';
        $arrays=[
            ['nom' =>'Afghanistan'  ,   'code' =>'AF'],
            ['nom' =>'Afrique du Sud'  ,   'code' =>'ZA'],
            ['nom' =>'Iles Aland'  ,   'code' =>'AX'],
            ['nom' =>'Albanie'  ,   'code' =>'AL'],
            ['nom' =>'Algérie'  ,   'code' =>'DZ'],
            ['nom' =>'Allemagne'  ,   'code' =>'DE'],
            ['nom' =>'Andorre'  ,   'code' =>'AD'],
            ['nom' =>'Angola'  ,   'code' =>'AO'],
            ['nom' =>'Anguilla'  ,   'code' =>'AI'],
            ['nom' =>'Antarctique'  ,   'code' =>'AQ'],
            ['nom' =>'Antigua et Barbuda'  ,   'code' =>'AG'],
            ['nom' =>'Arabie Saoudite'  ,   'code' =>'SA'],
            ['nom' =>'Argentine'  ,   'code' =>'AR'],
            ['nom' =>'Arménie'  ,   'code' =>'AM'],
            ['nom' =>'Aruba'  ,   'code' =>'AW'],
            ['nom' =>'Australie'  ,   'code' =>'AU'],
            ['nom' =>'Autriche'  ,   'code' =>'AT'],
            ['nom' =>'Azerbaïdjan'  ,   'code' =>'AZ'],
            ['nom' =>'Bahamas'  ,   'code' =>'BS'],
            ['nom' =>'Bahrein'  ,   'code' =>'BH'],
            ['nom' =>'Bangladesh'  ,   'code' =>'BD'],
            ['nom' =>'Barbade'  ,   'code' =>'BB'],
            ['nom' =>'Bélarus'  ,   'code' =>'BY'],
            ['nom' =>'Belgique'  ,   'code' =>'BE'],
            ['nom' =>'Bélize'  ,   'code' =>'BZ'],
            ['nom' =>'Bénin'  ,   'code' =>'BJ'],
            ['nom' =>'Bermudes'  ,   'code' =>'BM'],
            ['nom' =>'Bhoutan'  ,   'code' =>'BT'],
            ['nom' =>'Bolivie'  ,   'code' =>'BO'],
            ['nom' =>'Bonaire, Saint-Eustache et Saba'  ,   'code' =>'BQ'],
            ['nom' =>'Bosnie-Herzégovine'  ,   'code' =>'BA'],
            ['nom' =>'Botswana'  ,   'code' =>'BW'],
            ['nom' =>'Île Bouvet'  ,   'code' =>'BV'],
            ['nom' =>'Brésil'  ,   'code' =>'BR'],
            ['nom' =>'Brunéi Darussalam'  ,   'code' =>'BN'],
            ['nom' =>'Bulgarie'  ,   'code' =>'BG'],
            ['nom' =>'Burkina Faso'  ,   'code' =>'BF'],
            ['nom' =>'Burundi'  ,   'code' =>'BI'],
            ['nom' =>'Cap Vert'  ,   'code' =>'CV'],
            ['nom' =>'Îles Caïman '  ,   'code' =>'KY'],
            ['nom' =>'Cambodge'  ,   'code' =>'KH'],
            ['nom' =>'Cameroun'  ,   'code' =>'CM'],
            ['nom' =>'Canada'  ,   'code' =>'CA'],
            ['nom' =>'Chili'  ,   'code' =>'CL'],
            ['nom' =>'Chine'  ,   'code' =>'CN'],
            ['nom' =>'Île Christmas '  ,   'code' =>'CX'],
            ['nom' =>'Chypre'  ,   'code' =>'CY'],
            ['nom' =>'Îles Cocos'  ,   'code' =>'CC'],
            ['nom' =>'Colombie'  ,   'code' =>'CO'],
            ['nom' =>'Comores'  ,   'code' =>'KM'],
            ['nom' =>'Congo'  ,   'code' =>'CG'],
            ['nom' =>'République démocratique du Congo'  ,   'code' =>'CD'],
            ['nom' =>'Îles Cook'  ,   'code' =>'CK'],
            ['nom' =>'Corée du sud'  ,   'code' =>'KR'],
            ['nom' =>'Corée du nord',   'code' =>'KP'],
            ['nom' =>'Costa Rica'  ,   'code' =>'CR'],
            ['nom' =>'Côte d\'Ivoire'  ,   'code' =>'CI'],
            ['nom' =>'Croatie'  ,   'code' =>'HR'],
            ['nom' =>'Cuba'  ,   'code' =>'CU'],
            ['nom' =>'Curaçao'  ,   'code' =>'CW'],
            ['nom' =>'Danemark'  ,   'code' =>'DK'],
            ['nom' =>'Djibouti'  ,   'code' =>'DJ'],
            ['nom' =>'République Dominicaine'  ,   'code' =>'DO'],
            ['nom' =>'Dominique'  ,   'code' =>'DM'],
            ['nom' =>'Egypte'  ,   'code' =>'EG'],
            ['nom' =>'El Salvador'  ,   'code' =>'SV'],
            ['nom' =>'Emirats arabes unis'  ,   'code' =>'AE'],
            ['nom' =>'Equateur'  ,   'code' =>'EC'],
            ['nom' =>'Erythrée'  ,   'code' =>'ER'],
            ['nom' =>'Espagne'  ,   'code' =>'ES'],
            ['nom' =>'Estonie'  ,   'code' =>'EE'],
            ['nom' =>'Etats-Unis d\'Amérique'  ,   'code' =>'US'],
            ['nom' =>'Ethiopie'  ,   'code' =>'ET'],
            ['nom' =>'Îles Malouines'  ,   'code' =>'FK'],
            ['nom' =>'îles Féroé'  ,   'code' =>'FO'],
            ['nom' =>'Fidji'  ,   'code' =>'FJ'],
            ['nom' =>'Finlande'  ,   'code' =>'FI'],
            ['nom' =>'France'  ,   'code' =>'FR'],
            ['nom' =>'Gabon'  ,   'code' =>'GA'],
            ['nom' =>'Gambie'  ,   'code' =>'GM'],
            ['nom' =>'Géorgie'  ,   'code' =>'GE'],
            ['nom' =>'Géorgie du sud et les îles Sandwich du sud'  ,   'code' =>'GS'],
            ['nom' =>'Ghana'  ,   'code' =>'GH'],
            ['nom' =>'Gibraltar'  ,   'code' =>'GI'],
            ['nom' =>'Grèce'  ,   'code' =>'GR'],
            ['nom' =>'Grenade'  ,   'code' =>'GD'],
            ['nom' =>'Groenland'  ,   'code' =>'GL'],
            ['nom' =>'Guadeloupe'  ,   'code' =>'GP'],
            ['nom' =>'Guam'  ,   'code' =>'GU'],
            ['nom' =>'Guatemala'  ,   'code' =>'GT'],
            ['nom' =>'Guernesey'  ,   'code' =>'GG'],
            ['nom' =>'Guinée'  ,   'code' =>'GN'],
            ['nom' =>'Guinée-Bissau'  ,   'code' =>'GW'],
            ['nom' =>'Guinée équatoriale'  ,   'code' =>'GQ'],
            ['nom' =>'Guyana'  ,   'code' =>'GY'],
            ['nom' =>'Guyane française'  ,   'code' =>'GF'],
            ['nom' =>'Haïti'  ,   'code' =>'HT'],
            ['nom' =>'Îles Heard et MacDonald'  ,   'code' =>'HM'],
            ['nom' =>'Honduras'  ,   'code' =>'HN'],
            ['nom' =>'Hong Kong'  ,   'code' =>'HK'],
            ['nom' =>'Hongrie'  ,   'code' =>'HU'],
            ['nom' =>'Île de Man'  ,   'code' =>'IM'],
            ['nom' =>'Îles mineures éloignées des Etats-Unis'  ,   'code' =>'UM'],
            ['nom' =>'Îles vierges britanniques'  ,   'code' =>'VG'],
            ['nom' =>'Îles vierges des Etats-Unis'  ,   'code' =>'VI'],
            ['nom' =>'Inde'  ,   'code' =>'IN'],
            ['nom' =>'Territoire britannique de l\'océan indien'  ,   'code' =>'IO'],
            ['nom' =>'Indonésie'  ,   'code' =>'ID'],
            ['nom' =>'Iran'  ,   'code' =>'IR'],
            ['nom' =>'Iraq'  ,   'code' =>'IQ'],
            ['nom' =>'Irlande'  ,   'code' =>'IE'],
            ['nom' =>'Islande'  ,   'code' =>'IS'],
            ['nom' =>'Israël'  ,   'code' =>'IL'],
            ['nom' =>'Italie'  ,   'code' =>'IT'],
            ['nom' =>'Jamaïque'  ,   'code' =>'JM'],
            ['nom' =>'Japon'  ,   'code' =>'JP'],
            ['nom' =>'Jersey'  ,   'code' =>'JE'],
            ['nom' =>'Jordanie'  ,   'code' =>'JO'],
            ['nom' =>'Kazakhstan'  ,   'code' =>'KZ'],
            ['nom' =>'Kosovo'  ,   'code' =>'XK'],
            ['nom' =>'Kenya'  ,   'code' =>'KE'],
            ['nom' =>'Kirghizistan'  ,   'code' =>'KG'],
            ['nom' =>'Kiribati'  ,   'code' =>'KI'],
            ['nom' =>'Koweït'  ,   'code' =>'KW'],
            ['nom' =>'Laos'  ,   'code' =>'LA'],
            ['nom' =>'Lesotho'  ,   'code' =>'LS'],
            ['nom' =>'Lettonie'  ,   'code' =>'LV'],
            ['nom' =>'Liban'  ,   'code' =>'LB'],
            ['nom' =>'Libéria'  ,   'code' =>'LR'],
            ['nom' =>'Libye'  ,   'code' =>'LY'],
            ['nom' =>'Liechtenstein'  ,   'code' =>'LI'],
            ['nom' =>'Lituanie'  ,   'code' =>'LT'],
            ['nom' =>'Luxembourg'  ,   'code' =>'LU'],
            ['nom' =>'Macao'  ,   'code' =>'MO'],
            ['nom' =>'Macédoine'  ,   'code' =>'MK'],
            ['nom' =>'Madagascar'  ,   'code' =>'MG'],
            ['nom' =>'Malaisie'  ,   'code' =>'MY'],
            ['nom' =>'Malawi'  ,   'code' =>'MW'],
            ['nom' =>'Maldives'  ,   'code' =>'MV'],
            ['nom' =>'Mali'  ,   'code' =>'ML'],
            ['nom' =>'Malte'  ,   'code' =>'MT'],
            ['nom' =>'Îles Mariannes du nord'  ,   'code' =>'MP'],
            ['nom' =>'Maroc'  ,   'code' =>'MA'],
            ['nom' =>'Îles Marshall'  ,   'code' =>'MH'],
            ['nom' =>'Martinique'  ,   'code' =>'MQ'],
            ['nom' =>'Maurice'  ,   'code' =>'MU'],
            ['nom' =>'Mauritanie'  ,   'code' =>'MR'],
            ['nom' =>'Mayotte'  ,   'code' =>'YT'],
            ['nom' =>'Mexique'  ,   'code' =>'MX'],
            ['nom' =>'Etats Fédérés de Micronésie'  ,   'code' =>'FM'],
            ['nom' =>'Moldova'  ,   'code' =>'MD'],
            ['nom' =>'Monaco'  ,   'code' =>'MC'],
            ['nom' =>'Mongolie'  ,   'code' =>'MN'],
            ['nom' =>'Monténégro'  ,   'code' =>'ME'],
            ['nom' =>'Montserrat'  ,   'code' =>'MS'],
            ['nom' =>'Mozambique'  ,   'code' =>'MZ'],
            ['nom' =>'Myanmar'  ,   'code' =>'MM'],
            ['nom' =>'Namibie'  ,   'code' =>'NA'],
            ['nom' =>'Nauru'  ,   'code' =>'NR'],
            ['nom' =>'Népal'  ,   'code' =>'NP'],
            ['nom' =>'Nicaragua'  ,   'code' =>'NI'],
            ['nom' =>'Niger'  ,   'code' =>'NE'],
            ['nom' =>'Nigéria'  ,   'code' =>'NG'],
            ['nom' =>'Niue'  ,   'code' =>'NU'],
            ['nom' =>'Norfolk, Ile'  ,   'code' =>'NF'],
            ['nom' =>'Norvège'  ,   'code' =>'NO'],
            ['nom' =>'Nouvelle-Calédonie'  ,   'code' =>'NC'],
            ['nom' =>'Nouvelle-Zélande'  ,   'code' =>'NZ'],
            ['nom' =>'Oman'  ,   'code' =>'OM'],
            ['nom' =>'Ouganda'  ,   'code' =>'UG'],
            ['nom' =>'Ouzbékistan'  ,   'code' =>'UZ'],
            ['nom' =>'Pakistan'  ,   'code' =>'PK'],
            ['nom' =>'Palaos'  ,   'code' =>'PW'],
            ['nom' =>'Palestine'  ,   'code' =>'PS'],
            ['nom' =>'Panama'  ,   'code' =>'PA'],
            ['nom' =>'Papouasie-Nouvelle-Guinée'  ,   'code' =>'PG'],
            ['nom' =>'Paraguay'  ,   'code' =>'PY'],
            ['nom' =>'Pays-Bas'  ,   'code' =>'NL'],
            ['nom' =>'Pays inconnu'  ,   'code' =>'XX'],
            ['nom' =>'Pays multiples'  ,   'code' =>'ZZ'],
            ['nom' =>'Pérou'  ,   'code' =>'PE'],
            ['nom' =>'Philippines'  ,   'code' =>'PH'],
            ['nom' =>'Pitcairn'  ,   'code' =>'PN'],
            ['nom' =>'Pologne'  ,   'code' =>'PL'],
            ['nom' =>'Polynésie française'  ,   'code' =>'PF'],
            ['nom' =>'Porto Rico'  ,   'code' =>'PR'],
            ['nom' =>'Portugal'  ,   'code' =>'PT'],
            ['nom' =>'Qatar'  ,   'code' =>'QA'],
            ['nom' =>'République arabe syrienne'  ,   'code' =>'SY'],
            ['nom' =>'République centrafricaine'  ,   'code' =>'CF'],
            ['nom' =>'Réunion'  ,   'code' =>'RE'],
            ['nom' =>'Roumanie'  ,   'code' =>'RO'],
            ['nom' =>'Royaume-Uni de Grande-Bretagne'  ,   'code' =>'GB'],
            ['nom' =>'Russie'  ,   'code' =>'RU'],
            ['nom' =>'Rwanda'  ,   'code' =>'RW'],
            ['nom' =>'Sahara occidental'  ,   'code' =>'EH'],
            ['nom' =>'Saint-Barthélemy'  ,   'code' =>'BL'],
            ['nom' =>'Saint-Kitts-et-Nevis'  ,   'code' =>'KN'],
            ['nom' =>'Saint-Marin'  ,   'code' =>'SM'],
            ['nom' =>'Saint-Martin (partie française)'  ,   'code' =>'MF'],
            ['nom' =>'Saint-Martin (partie néerlandaise)'  ,   'code' =>'SX'],
            ['nom' =>'Saint-Pierre-et-Miquelon'  ,   'code' =>'PM'],
            ['nom' =>'Saint-Siège'  ,   'code' =>'VA'],
            ['nom' =>'Saint-Vincent-et-les-Grenadines'  ,   'code' =>'VC'],
            ['nom' =>'Sainte-Hélène'  ,   'code' =>'SH'],
            ['nom' =>'Sainte-Lucie'  ,   'code' =>'LC'],
            ['nom' =>'Îles Salomon'  ,   'code' =>'SB'],
            ['nom' =>'Samoa'  ,   'code' =>'WS'],
            ['nom' =>'Samoa américaines'  ,   'code' =>'AS'],
            ['nom' =>'Sao Tomé-et-Principe'  ,   'code' =>'ST'],
            ['nom' =>'Sénégal'  ,   'code' =>'SN'],
            ['nom' =>'Serbie'  ,   'code' =>'RS'],
            ['nom' =>'Seychelles'  ,   'code' =>'SC'],
            ['nom' =>'Sierra Leone'  ,   'code' =>'SL'],
            ['nom' =>'Singapour'  ,   'code' =>'SG'],
            ['nom' =>'Slovaquie'  ,   'code' =>'SK'],
            ['nom' =>'Slovénie'  ,   'code' =>'SI'],
            ['nom' =>'Somalie'  ,   'code' =>'SO'],
            ['nom' =>'Soudan'  ,   'code' =>'SD'],
            ['nom' =>'Soudan du Sud'  ,   'code' =>'SS'],
            ['nom' =>'Sri Lanka'  ,   'code' =>'LK'],
            ['nom' =>'Suède'  ,   'code' =>'SE'],
            ['nom' =>'Suisse'  ,   'code' =>'CH'],
            ['nom' =>'Suriname'  ,   'code' =>'SR'],
            ['nom' =>'Svalbard et île Jan Mayen'  ,   'code' =>'SJ'],
            ['nom' =>'Swaziland'  ,   'code' =>'SZ'],
            ['nom' =>'Tadjikistan'  ,   'code' =>'TJ'],
            ['nom' =>'Taïwan'  ,   'code' =>'TW'],
            ['nom' =>'Tanzanie'  ,   'code' =>'TZ'],
            ['nom' =>'Tchad'  ,   'code' =>'TD'],
            ['nom' =>'République Tchèque'  ,   'code' =>'CZ'],
            ['nom' =>'Terres australes françaises'  ,   'code' =>'TF'],
            ['nom' =>'Thaïlande'  ,   'code' =>'TH'],
            ['nom' =>'Timor-Leste'  ,   'code' =>'TL'],
            ['nom' =>'Togo'  ,   'code' =>'TG'],
            ['nom' =>'Tokelau'  ,   'code' =>'TK'],
            ['nom' =>'Tonga'  ,   'code' =>'TO'],
            ['nom' =>'Trinité-et-Tobago'  ,   'code' =>'TT'],
            ['nom' =>'Tunisie'  ,   'code' =>'TN'],
            ['nom' =>'Turkménistan'  ,   'code' =>'TM'],
            ['nom' =>'Îles Turks-et-Caïcos'  ,   'code' =>'TC'],
            ['nom' =>'Turquie'  ,   'code' =>'TR'],
            ['nom' =>'Tuvalu'  ,   'code' =>'TV'],
            ['nom' =>'Ukraine'  ,   'code' =>'UA'],
            ['nom' =>'Uruguay'  ,   'code' =>'UY'],
            ['nom' =>'Vanuatu'  ,   'code' =>'VU'],
            ['nom' =>'Vatican : voir Saint-Siège'  ,   'code' =>'0'],
            ['nom' =>'Venezuela'  ,   'code' =>'VE'],
            ['nom' =>'Vietnam'  ,   'code' =>'VN'],
            ['nom' =>'Wallis et Futuna'  ,   'code' =>'WF'],
            ['nom' =>'Yémen'  ,   'code' =>'YE'],
            ['nom' =>'Zambie'  ,   'code' =>'ZM'],
            ['nom' =>'Zimbabwe'  ,   'code' =>'ZW'],

        ];
        $i=1;
        foreach($arrays as $key=>$array){
            $arrays[$key]['id'] = $i;
            $i++;
        }

        $this->arguments=$arrays;
    }





    private function verifierSequence(){
        $max=null;
        $arguments=collect($this->arguments);
        $argumentMax=$arguments->max('id');
        $result=DB::table($this-> table)->max('id');

        if($result>$argumentMax)$max=$result+1;
        elseif ($result<=$argumentMax)$max=$argumentMax;
        // dd($result,$argumentMax);
        // dd($max);

        if(!is_null($max)){
            $sql='ALTER SEQUENCE '.$this->table.'_id_seq restart with '.$max;
            // DB::statement($sql);

        }
    }



    public function run(){
        DB::table($this->table)->insertOrIgnore($this->arguments);
        // $this->verifierSequence();
    }

}
